### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by mburns** [jirwin/treslek#42]
It would be great to have a meeting announcement/reminder. Either by parsing a (simple) vcal file or a caldnar npm library. This would be nice for team meetings or open invites to people in a given channel.
- weekdays (M-F) standups
- weekly/bi-weekly recurring meetings
- once-off meetings (similar to `!remindme`, but given a datetime stamp.
- include a link for would-be participants to click.

**Comment by jirwin** [comment]
Started working on this here: https://github.com/jirwin/treslek-calendar
