### ISSUE TITLE
github issue plugin

### ISSUE THREAD

**Issue by mburns** [jirwin/treslek#47]
`!issue <repo> <title>` where:

* `<repo>` is the github namespace (or implied by a default config) of the repo
* `<title>` is the rest of the line, possibly broken up on the word at <= 80 characters, with the rest being put as the `<body>` of the issue.

**Comment by jirwin** [comment]
Fixed in treslek-github

**Comment by jjbuchan** [comment]
@jirwin if you felt like expanding on the github plugin, I wrote an issue searcher a couple months ago - https://github.com/jjbuchan/treslek-gh-issue-search.  Could combine the functionality.
